name: Publish Evaluation Images

on:
  push:
    branches:
      - main
    paths: ["evaluation/**"]

jobs:
  publish_memhog:
    name: Publish memhog_wff image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: evaluation/build/memhog
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fastfreeze4service_migration/memhog:latest
